Mathy.Web/Controllers/CoefficientController.cs
using Aspose.Cells;
using Mathy.DAL;
using Mathy.Model.Entity;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;

namespace Mathy.Web.Controllers
{
    public class CoefficientController : Controller
    {

        public ActionResult Index(string coefficientName, int pageIndex)
        {
            pageIndex = pageIndex == 0 ? 1 : pageIndex;
            var dal = new CoefficientDAL();
            var result = dal.GetCoefficients(new Model.Common.PageInfo { PageIndex = pageIndex, PageSize = 5 }, coefficientName);
            ViewBag.pageIndex = pageIndex;
            ViewBag.TotalPage = result.Page.TotalCount / result.Page.PageSize + 1;
            ViewBag.CoefficientName = coefficientName;

            var user = new UserEntity();
            user.Email = HttpContext.Request.Cookies["user"].Value;
            user.Company = "";
            user.Role = HttpContext.Request.Cookies["role"].Value;
            ViewBag.User = user;
            return View(result.Data);
        }

        public ActionResult CreateCoefficient(int coefficientID, bool ro = false)
        {
            CoefficientVM vm;
            if (coefficientID == 0)
            {
                vm = new CoefficientVM();
                vm.CoefficientDetails = new List<CoefficientDetail>();
            }
            else
            {
                var dal = new CoefficientDAL();
                var c = dal.GetCoefficient(coefficientID);
                vm = new CoefficientVM();
                vm.CoefficientID = c.CoefficientID;
                vm.CoefficientName = c.CoefficientName;
                vm.CoefficientContent = c.CoefficientContent;
                vm.CoefficientDetails = new CoefficientDAL().GetCoefficientDetail(coefficientID);
            }
            ViewBag.ro = ro;
            return View(vm);
        }

        [HttpPost]
        public ActionResult ImportGrid(HttpPostedFileBase file)
        {
            var workbook = new Workbook(file.InputStream);
            int headRow = -1;
            var sheet = workbook.Worksheets[0];
            foreach (Cell c in sheet.Cells)
            {
                if (c.Value != null)
                    headRow = c.Row;
                break;
            }
            if (headRow < 0)
            {
                return Content("列头读取有误，请检查！");
            }
            var heads = new Dictionary<string, int>();
            try
            {
                var row = sheet.Cells.GetRow(headRow);
                for (var i = 0; i <= sheet.Cells.MaxDataColumn; i++)
                {
                    heads.Add(row.GetCellByIndex(i).Value.ToString(), i);
                }
            }
            catch (Exception ex)
            {
                return Content("列名称有误，请检查！");
            }
            var list = new List<CoefficientDetail>();
            foreach (Row r in sheet.Cells.Rows)
            {
                if (r.Index != headRow)
                {
                    foreach (var n in heads)
                    {
                        var cell = r.GetCellOrNull(n.Value);
                        var cValue = cell == null ? "0" : cell.Value.ToString();

                        decimal dv = 0;
                        if (decimal.TryParse(cValue, out dv))
                        {
                            list.Add(new CoefficientDetail
                            {
                                CoefficientDetailIndex = n.Value,
                                CoefficientDetailName = n.Key,
                                CoefficientDetailRow = r.Index,
                                CoefficientDetailValue = dv
                            });
                        }
                        else
                        {
                            string msg = string.Format("行{0}列{1}数据有误，请检查！", r.Index, n.Value);
                            return Content(msg);
                        }
                    }
                }
            }
            Session.Add("coeData", list);
            return View(list);
        }

        [HttpPost]
        public string AddCoefficient(CoefficientVM coefficient)
        {
            var dal = new CoefficientDAL();
            var details = (List<CoefficientDetail>)Session["coeData"];
            if (details == null || details.Count == 0)
            {
                coefficient.CoefficientID = -1;
                return JsonConvert.SerializeObject(coefficient);
            }
            using (var tran = dal.GetTransaction())
            {
                if (coefficient.CoefficientID > 0)
                {
                    dal.UpdateCoefficient(coefficient, tran);
                }
                else
                {
                    if (dal.GetCoefficientDetail(coefficient.CoefficientName).Count > 0)
                    {
                        coefficient.CoefficientID = -2;
                        return JsonConvert.SerializeObject(coefficient);
                    }
                    coefficient.Creator = HttpContext.Request.Cookies["user"].Value;
                    coefficient.CoefficientID = dal.AddCoefficient(coefficient, tran);
                }
                details.ForEach(m => m.CoefficientID = coefficient.CoefficientID);
                dal.DeleteCoefficientDetails(coefficient.CoefficientID, tran);
                dal.AddCoefficientDetails(details, tran);
                tran.Commit();
            }
            return JsonConvert.SerializeObject(coefficient);
        }

        [HttpPost]
        public bool DeleteCoefficient(int autoID)
        {
            return new CoefficientDAL().DeleteCoefficient(autoID);
        }
    }
}

Mathy.Web/Views/Coefficient/CreateCoefficient.cshtml
@using Mathy.Model.Entity
@model CoefficientVM

@{
    ViewBag.Title = "编辑";
    bool readOnly = (Boolean)ViewBag.ro;
}

@section scripts {
    <script src="/Scripts/grid.js"></script>
    <script src="/Scripts/ui.js"></script>
    <script src="/Scripts/realtime-edit.js"></script>
    <script language="javascript">
        function saveCoe() {
            $.ajax({
                url: "/Coefficient/AddCoefficient",
                dataType: "json",
                contentType: "application/json",
                method: "POST",
                data: JSON.stringify({
                    CoefficientID: $("#CoefficientID").val(),
                    CoefficientName: $("#CoefficientName").val(),
                    CoefficientContent: editor.txt.html()
                }),
                success: function (res) {
                    if (res.CoefficientID > 0) {
                        alert("保存成功");
                        $("#CoefficientID").val(res.CoefficientID);
                    }
                    else {
                        if (res.CoefficientID === -1) {
                            alert("请导入明细");
                        }
                        else if (res.CoefficientID === -2) {
                            alert("已有相同名称的系数表");
                        }
                        else {
                            alert("保存失败");
                        }
                    }
                },
                error: function (res) {
                    alert("服务器异常，请联系管理员。");
                }
            });
        }
        function importGrid() {
            popup(
                "导入",
                {
                    width: 500,
                    height: 400,
                    okButton: true,
                    cancelButton: true,
                    ok: function () {
                        var files = $("#select-file")[0].files;
                        var form = new FormData();
                        form.append('file', files[0]);
                        $.ajax({
                            url: '/Coefficient/ImportGrid',
                            type: "POST",
                            data: form,
                            contentType: false,
                            processData: false,
                            success: function (result) {
                                $('#grid1').html(result);
                                closePopup();
                            },
                            error: function (result) {
                                alert(result.responseJSON.message);
                            }
                        });

                    },
                    cancel: function () {
                        closePopup();
                    }
                },
                "<table><tr><td>选择文件</td><td><input id='select-file' type='file'></input></td></tr></table><br/><div id='message-dialog'></div>");
        }
    </script>
}

<div id="previewMessage" class="error-message"></div>
<br />

<div id="editTab">
    <input hidden="hidden" id="CoefficientID" value="@Model.CoefficientID" />
    <table class="table">
        <tbody>
            <tr>
                <td width="10%">系数表名称</td>
                <td width="90%"> <input id="CoefficientName" type="text" value="@Model.CoefficientName" style="display: block; width: 100%;" /> </td>
            </tr>
            <tr>
                <td width="10%">说明</td>
                <td width="90%">
                    @Html.Partial("~/Views/Shared/EditorView.cshtml", string.IsNullOrEmpty(Model.CoefficientContent) ? "" : Model.CoefficientContent)
                </td>
            </tr>
        </tbody>
    </table>
    <br />
    @if (!readOnly)
    {
        <input type="button" class="btn btn-primary" value="导入系数表" onclick="importGrid();" />
    }
    else
    {
        <input type="button" class="btn btn-primary" value="系数表明细" />
    }
    <div id="grid1">
        @Html.Partial("~/Views/Coefficient/ImportGrid.cshtml", Model.CoefficientDetails)
    </div>
    <br />
    <hr />
    <div id="message" class="error-message"></div>
    <br />
    @if (!readOnly)
    {
        <input class="btn btn-primary" type="button" value="保存" onclick=" saveCoe();" />
    }
</div>

Mathy.Web/Views/Coefficient/ImportGrid.cshtml
@using Mathy.Model.Entity
@model  List<CoefficientDetail>

@if (Model.Count > 0)
{
    <table class="table bordered">
        <thead>
            <tr>
                <th>行号</th>
                @foreach (var n in Model.OrderBy(m => m.CoefficientDetailIndex).ToLookup(m => new { m.CoefficientDetailIndex, m.CoefficientDetailName }))
                {
                    <th>@n.Key.CoefficientDetailName</th>
                }
            </tr>
        </thead>
        <tbody>

            @foreach (var n in Model.OrderBy(m => m.CoefficientDetailRow).ToLookup(m => m.CoefficientDetailRow))
            {
                <tr>
                    <td>@n.Key</td>
                    @foreach (var m in n.OrderBy(m => m.CoefficientDetailIndex))
                    {
                        <td>@m.CoefficientDetailValue</td>
                    }
                </tr>
            }
        </tbody>
    </table>
}

Mathy.Web/Views/Coefficient/Index.cshtml
@using Mathy.Model.Entity
@model IEnumerable<Coefficient>

@{
    Layout = "~/Views/Shared/_Login.cshtml";
    var user = ViewBag.User as UserEntity;
}

@section scripts {

    <script language="javascript">

        $(function () {
            innitPage(@ViewBag.pageIndex, @ViewBag.TotalPage, SearchPage);
            window.parent.reheight();
        })

        function SearchPage(page) {
            var url = "/Coefficient/index/" + "?pageIndex=" + page;

            var CoefficientName = $('#CoefficientName').val();
            if (CoefficientName.length > 0) {
                url += "&CoefficientName=" + CoefficientName + "&";
            }
            window.location.href = url;
        }

        function deleteCoefficient(autoID) {

            if (confirm("是否确定删除？删除后无法恢复。")) {

                $.ajax({
                    url: "/Coefficient/DeleteCoefficient?autoID=" + autoID,
                    method:'POST',
                    success: function (res) {
                        alert("删除成功");
                        SearchPage(1);
                    },
                    error: function (res) {
                        alert(res.responseJSON.message);
                    }
                });
            }
        }

    </script>
}
<div class="gray-bg reheight">
    <div class="wrapper wrapper-content animated fadeIn">
        <div class="col-lg-12">
            <div class="row">
                <div class="col-sm-2">
                    <div class="form-group">
                        <label class="control-label" for="product_name">系数表名称</label>
                        <input type="text" id="CoefficientName" value="@ViewBag.CoefficientName" placeholder="系数表名称" class="form-control">
                    </div>
                </div>
                <a class="btn btn-primary" style="margin-top:24px;width:100px" onclick="SearchPage(@ViewBag.pageIndex)">查询</a>
                <a class="btn btn-primary J_menuItem_Child" style="margin-top:24px;width:100px" href="@Url.Action("CreateCoefficient","Coefficient",new {coefficientID=0 })">新增系数表</a>
            </div>
            <div id="Paginator"> <ul id="pageLimit"></ul> </div>
            <div class="table-responsive gray-bg">
                @foreach (var n in Model)
                {
                    <div class="media list-group-item  gray-bg">
                        <div class="media-body">
                            <h4 class="media-heading">
                                @n.CoefficientName
                            </h4>
                            <h5>@(n.Creator + "  " + n.CreateTime)</h5>
                            @Html.Raw(n.CoefficientContent)
                        </div>
                        <div class="media" style="margin-top:10px">
                            <a href="@Url.Action("CreateCoefficient","Coefficient",new {coefficientID =n.CoefficientID,ro= true })" class="btn-sm btn-info J_menuItem_Child">查看</a>
                            @if (user.Role == "1")
                            {
                                <a href="@Url.Action("CreateCoefficient", "Coefficient", new { coefficientID = n.CoefficientID, ro = false })" class="btn-sm btn-primary J_menuItem_Child">编辑</a>
                                <a href="javascript:viod(0)" onclick="deleteCoefficient(@n.CoefficientID)" class="btn-sm btn-danger"> 删除</a>
                            }
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>